server:
  port: 8081

spring:
  application:
    name: nexus-user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nexus}
    username: ${SPRING_DATASOURCE_USERNAME:nexus}
    password: ${SPRING_DATASOURCE_PASSWORD:nexus}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
